### PR TITLE
Fix #4 and update codebase

### LINKED ISSUE #4: Can't be build anymore because of yanked crate
I would love to use this libary in a project but it can't be build anymore, because the crate `reqwest` needs `native-tls`, which requires a yanked version of `secruity-framework`

Heres my full error:

```
error: failed to select a version for the requirement `security-framework = "^0.1.13"`
candidate versions found which didn't match: 2.8.2, 2.8.1, 2.8.0, ...
location searched: crates.io index
required by package `native-tls v0.1.3`
    ... which satisfies dependency `native-tls = "^0.1.3"` of package `reqwest v0.8.5`
    ... which satisfies dependency `reqwest = "^0.8.5"` of package `untis v0.2.1`
    ... which satisfies dependency `untis = "^0.2.1"` of package `untis-rust-test v0.1.0 (/home/alex/dev/untis-rust-test)`
```

### PR DESCRIPTION
**Pull request by arnimattr**
To fix #4 I upgraded reqwest to its newest version. This version supports async requests, but I used the `rewqest::blocking` client as I figured that users of this library can always use it within their own asynchronous code if they need to.
A nice side effect of the upgrade was also that we don't need to handle cookies ourselves anymore :)

I also refactored the code base, in particular:
- renamed modules & structs
- improved RPC error handling (related to #1)
- changed the API of the `untis::Client` struct; The constructor now creates a new session (previously had to call `.login()`) and when the client is dropped from memory, it automatically logs out. You can take a look at this new API in the examples
- added methods for accessing specific timetables
- added methods for searching schools, accessing teachers and students, fetching the current school year etc.
- added documentation
- basic GitHub workflows for verifying that everything still works

These are relatively big (and breaking) changes, so I can completely understand if you don't want a new contributor to completely change your API.

### CODE REVIEW

**Comment by luleyleo** [comment]
Thanks for the PR! I'll try to review it sometime soon :)

**Comment by luleyleo** [comment]
Looks good over all! Could you remove the CI file for now? Then we can merge this.

**Comment by arnimattr** [comment]
I forgot to mention that because the new school year hasn't started yet, I haven't been able to test the `timetable`, `holidays`, `current_schoolyear`, and some other methods. Manually parsing some old API responses I still had saved worked fine, but I can't verify that everything is 100% correct.
Should we wait one more week or just release a patch in case something is broken?

**Comment by arnimattr** [comment]
I just tested all the methods - seems to work

**Pull request merged**
